#!/usr/bin/env python3
"""Generate _redirects from the URL map and the 1A cut.

Format is the Netlify / Cloudflare Pages `_redirects` file: one rule per line,
`<from> <to> <status>`, first match wins. Generated rather than hand-written so
it cannot drift from content/selection.json, and so every target is checked
against the actual build before it ships.

Usage:  python3 tools/gen_redirects.py [--check]
"""
import csv, json, os, sys, urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

sel = json.load(open("content/selection.json", encoding="utf-8"))
cut = {f"/artworks/{k}": v for k, v in sel["works_dropped"].items()}
cut.update(sel["orphans_dropped"])


def exists(p):
    p = urllib.parse.unquote(p).strip("/")
    return p == "" or os.path.isfile(f"{p}/index.html") or os.path.isfile(p)


def resolve(dest):
    """Follow the chain so no rule points at another redirect.

    A Chinese URL may point at an English work the redesign then cut. Chained
    redirects leak ranking signal and cost a round trip, so collapse them here.
    """
    d = dest if dest.endswith("/") else dest + "/"
    for _ in range(5):
        if d.rstrip("/") in cut:
            d = cut[d.rstrip("/")]
            d = d if d.endswith("/") else d + "/"
            continue
        return d
    raise SystemExit(f"redirect loop at {dest}")


rules, seen = [], set()
for r in csv.DictReader(open("seo/url-map.csv", encoding="utf-8")):
    src = r["path_decoded"]
    if src in seen:
        continue
    if r["action"] == "301":
        dst = resolve(r["destination_or_note"].split("#")[0].strip())
    elif r.get("post_redesign") == "DROPPED BY 1A CUT":
        dst = resolve(r["redirect_to"])
    else:
        continue
    seen.add(src)
    rules.append((src, dst))

bad = [(s, d) for s, d in rules if not exists(d)]
if bad:
    for s, d in bad:
        print(f"TARGET MISSING  {s} -> {d}", file=sys.stderr)
    sys.exit(1)

if "--check" in sys.argv:
    print(f"{len(rules)} rules, all targets resolve")
    sys.exit(0)

width = max(len(s) for s, _ in rules) + 2
out = [
    "# Redirects for the Wix -> static migration. Generated by",
    "# tools/gen_redirects.py from seo/url-map.csv and content/selection.json.",
    "# Do not hand-edit: change the source and regenerate.",
    "#",
    "# Format is shared by Netlify and Cloudflare Pages. First match wins, so",
    "# the explicit rules must stay above the wildcards at the foot.",
    "#",
    f"# {len(rules)} explicit rules. /artwork/ and /exhibition/ (singular) were",
    "# the Chinese-language site; they now resolve to the bilingual page.",
    "",
]
for src, dst in sorted(rules):
    out.append(f"{src:<{width}}{dst:<42}301")

out += [
    "",
    "# Catch-all for any Chinese URL not enumerated above. Must stay last:",
    "# the explicit rules take precedence.",
    f"{'/artwork/*':<{width}}{'/artworks/:splat':<42}301",
    f"{'/exhibition/*':<{width}}{'/exhibitions/:splat':<42}301",
    "",
]

open("_redirects", "w", encoding="utf-8").write("\n".join(out))
print(f"_redirects written — {len(rules)} explicit rules + 2 catch-alls")
